### ISSUE TITLE
Dynamic new page creation

### ISSUE THREAD

**Issue by SupremeSalvatore** [gwenf/gridsome-strapi-tutorial#1]
https://github.com/gwenf/gridsome-strapi-tutorial/blob/0f0eaa8a0827faf39e4217ce7c46d3e6009eb82d/e-vents-front/src/templates/Event.vue#L11
I'm not sure this should a string like this, it should be a dynamic variable? But since I'm learning maybe you can explain me. Thanks!

**Comment by fangqiank** [comment]
<page-query>
query($id: ID!) {
  event(id: $id) {
    id
    title
    description
    duration
    price
    date
  }
}
</page-query>

**Comment by fangqiank** [comment]
> https://github.com/gwenf/gridsome-strapi-tutorial/blob/0f0eaa8a0827faf39e4217ce7c46d3e6009eb82d/e-vents-front/src/templates/Event.vue#L11
> 
> 
> I'm not sure this should a string like this, it should be a dynamic variable? But since I'm learning maybe you can explain me. Thanks!

`<page-query>
query($id: ID!) {
  event(id: $id) {
    id
    title
    description
    duration
    price
    date
  }
}
</page-query>`

**Comment by SupremeSalvatore** [comment]
This is working now as expected thanks!
